implement additional driver.Rows interfaces
opencensus-integrations/ocsql pull request #20
Opened 2018-10-11 13:37 UTC by hugorut

Currently type `ocRows` doesn't implement the additional `driver.Rows` interfaces. 

* `driver.RowsNextResultSet`
* `driver.RowsColumnTypePrecisionScale`
* `driver.RowsColumnTypeNullable`
* `driver.RowsColumnTypeLength`
* `driver.RowsColumnTypeDatabaseTypeName`

This causes issues in available public methods such as `sql.Rows.ColumnTypes` which does explicit interface checking to populate results.

This PR fixes this issue by implementing the necessary interface methods.

2018-10-12 09:39 UTC, basvanbeek requested changes
Some minor nits to iron out and then it looks ok to me.

2018-10-12 09:39 UTC, basvanbeek commented on driver.go
> +	return nil
`driver.go` states "NextResultSet should return io.EOF when there are no more result sets."

Probably it's better to send `io.EOF` if underlying rows implementation does not support driver.RowsNextResultSet

2018-10-12 09:39 UTC, basvanbeek commented on driver.go
> +// ColumnTypePrecisionScale calls the implements the driver.RowsColumnTypePrecisionScale for ocRows.
Please move around these method implementations to follow the same order as their interface definitions in the driver package.

2018-10-12 09:39 UTC, basvanbeek commented on driver.go
> +	return nil
This method implementation is not transparent. The code actually using this interface does the following:

```go
if prop, ok := rowsi.(driver.RowsColumnTypeScanType); ok {
	ci.scanType = prop.ColumnTypeScanType(i)
} else {
	ci.scanType = reflect.TypeOf(new(interface{})).Elem()
}
```

So either return `reflect.TypeOf(new(interface{})).Elem()` (brittle as the go sql code using this functionality might change)  or hide this interface extension when wrapped drivers do not implement this interface

2018-10-12 14:11 UTC, hugorut commented
@basvanbeek changes made + addition of tests

2018-10-15 08:18 UTC, hugorut commented
travis build seemed to be failing because of a recent patch to the golint library. It now enforces that you import using:

```
go get -u golang.org/x/lint/golint 
```

see issue for more details: https://github.com/golang/lint/issues/415

Have updated the travis script to reflect.

2018-10-22 08:08 UTC, hugorut commented
@basvanbeek any chance we can get this merged?

2018-10-22 17:40 UTC, basvanbeek commented
@hugorut thank you for the contribution, greatly appreciated. I'd like a couple of changes for consistency's sake:

We have enhancement/optional interface logic happening for `ocDriver` and `ocConn` too. These have been handled in a specific way by having the underlying implementation implement all optional interface methods and then at wrapping time inspect which interfaces are supported by the underlying driver. From there the actual implementation is wrapped by structs enabling only the supported interfaces or if all interfaces are supported the implementation is returned unwrapped. 

The functions handling the wrapping are called `wrapDriver` and `wrapConn`. So in this case `newRows` would become `wrapRows` and should handle the logic for the Rows interfaces the same way.

The majority of your test suite can then also be removed because we can compile time assert the `ocRows` implementation against the interfaces.

It would be great to have proper tests for all the wrap functions (testing each combination of interfaces being correctly opened up) but this is similarly brittle as the actual wrapping code if written by hand.

I expect these tests to be added in the future but they should be auto generated.

2018-10-29 11:43 UTC, hugorut commented
@basvanbeek sorry for the radio silence on this. Snowed with other things.

Apologies that I did not see the `wrap` functions before. However, the implementation within those functions will not work for the driver.Rows additional interfaces :(.

The current implementation in `wrapStmt` (for example) works because the underlying additional interfaces are isolated. e.g. `driver.tmtExecContext` contains a single method. However with the `driver.Rows` interfaces they *compose* the interface from the parent `driver.Rows` interface. e.g:

```go
type RowsColumnTypeScanType interface {
	Rows
	ColumnTypeScanType(index int) reflect.Type
}
```

hence if we do something like this:

```go
return struct {
       driver.Rows
       driver.RowsColumnTypeScanType
}{rs, rcts}
``` 

go compilation will error with:

```bash
struct { driver.Rows; driver.RowsColumnTypeScanType }.Close is ambiguous
```

The solution is to create concrete struct types for each interface combination. However this feels like overkill. Let me know your thoughts.

2018-10-29 13:12 UTC, basvanbeek commented
No problem, we all get busy. Yeah I've noticed the composition too. Not sure why they did that but we have to live with it. We can however declare our own local (even unexported) interfaces and use those to achieve the desired effect. Implicit interfaces FTW.

2018-10-29 13:13 UTC, hugorut commented
Cool perfect was going to suggest such an approach. Will implement this afternoon.

2018-10-29 13:15 UTC, basvanbeek commented
Awesome, thank you for hanging in there. Transparency of this wrapper without introducing side effects is super important to me.

2018-10-29 16:51 UTC, hugorut commented
So I just realised if we take the switch composition approach we're going to have to write 64 combinations of struct initialisation. Not only will this be cumbersome but also could be open to a lot of user error. I'm kinda unsure of the best way to achieve what we want without simply going back to the `ocRows` implementing a generic version of the additional interfaces which calls the parent if it's implemented.  Thoughts?

2018-10-29 17:40 UTC, basvanbeek commented
Fortunately not needed. We only have two compositions that matter. One with and one without `driver.RowsColumnTypeScanType`. The others are safe to have return default values if the underlying driver does not support them.

2018-10-29 18:02 UTC, hugorut commented
Ok phew great. I thought I was going to have to do that for every branch

2018-11-28 15:27 UTC, basvanbeek commented
@hugorut are you ok with me closing this PR in favor of continuing in PR #26?

2018-11-28 15:31 UTC, hugorut commented
I'll close now #20 is in play

2018-11-28 15:31 UTC, closed without merging