Added WithDefaultAttributes()
opencensus-integrations/ocsql pull request #4
Opened 2018-08-13 17:52 UTC by bgpat

## WHY

I'm trying to send the tracing span with [opencensus-go-exporter-datadog](https://github.com/DataDog/opencensus-go-exporter-datadog). DataDog UI has 4 buttons that filter by the span type. By default, the span type will be set `Custom` in *opencensus-go-exporter-datadog*.

<img width="358" alt="image" src="https://user-images.githubusercontent.com/6045753/44047145-896b58ac-9f68-11e8-8dbe-fcddaba1a1fc.png">

We can set the span type by an attribute of [`span.type`](https://github.com/DataDog/dd-trace-go/blob/2ef32813748b754e58e3b9336fd257aec967515b/ddtrace/ext/tags.go#L34-L35), but ocsql cannot inject custom attributes now. I hope a type of the span sampled by ocsql is categorized as `DB`.

## WHAT

I implemented `WithDefaultAttributes()` and injected for each methods.

2018-08-23 09:38 UTC, basvanbeek commented
thanks @bgpat, I just came back from my summer holiday and will get to a review shortly.

2018-08-24 14:10 UTC, basvanbeek requested changes
I'm in favor of adding the ability to have default attributes but I have a couple of concerns with the current implementation:

- if no default attributes are provided it is possible for this PR to call `AddAttributes` with no payload in various locations. This no-op is expensive as AddAttributes will always try to acquire a lock.
- in various `append` calls you use `c.options.DefaultAttributes` as slice source, which is not goroutine safe. You will have to copy the DefaultAttributes slice.
- WithDefaultAttributes always appends to previously set attributes. I expect the `WithDefaultAttributes` call to replace rather than append.

2018-08-26 17:51 UTC, bgpat commented
I fixed what you pointed out.

2018-09-17 02:01 UTC, odeke-em commented
/cc @basvanbeek

2018-09-20 14:14 UTC, merged

2018-09-20 14:14 UTC, basvanbeek commented
Thank you @bgpat !